export HUBOT_AUTH_ADMIN=
export HEROKU_URL=
export HUBOT_HIPCHAT_JID=
export HUBOT_HIPCHAT_PASSWORD=
export HUBOT_HIPCHAT_ROOMS=

export HUBOT_BROWSERSTACK_USERNAME=
export HUBOT_BROWSERSTACK_API_KEY=
export HUBOT_HOSTNAME=